name: line lint
on:
  push:
    branches:
      - main
jobs:
  line-lint:
    name: line lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: linelint
        uses: shoothzj/linelint@main
